### ISSUE TITLE
What's going on with the recruitment strategy?

### ISSUE THREAD

**Issue by thomasmorgan** [Ruben222/Social-learning-spite#2]
It looks like:

- There's one ppt per network
- But there's also only 1 network - presumably this will be increased later?
- But, if so, the network selection algorithm is the default and so a single participant will play through all networks anyway.
- Because the next ppt is not recruited until the first has finished, the first ppt will fill all networks and then the experiment will stop.

Am I missing something? Why not have multiple networks, or multiple participants per network, and recruit multiple participants at once?

**Comment by Rowatsonn** [comment]
For now, I only had it set to one network for debugging purposes. Yes, the intention is to have multiple networks playing simultaneously. Though, based on what you said, it sounds like I have something else going wrong as I certainly wouldn't want the same participant going through multiple networks. Is there something I can change?

**Comment by thomasmorgan** [comment]
So I think I've fixed this with three commits.
First assign people to a single network, then send them to the end: b7f3ecda1d99d40431760a5ac71eb69de8e9bb42
Then change recruit so you only recruit people at the start: 5bb90d3230de25b1a291f380dafe16fda096056e
Lastly, start off by recruiting all the people you need: 5838cb3cd9cd66970845e7a264180b7a0562d20c

Does this meet the goals of your experiment?

**Comment by Rowatsonn** [comment]
Yep, I think so. Thanks!

**Comment by thomasmorgan** [comment]
OK, great, I'll close the issue.
