### ISSUE TITLE
Front end does not wait for info requests to resolve

### ISSUE THREAD

**Issue by thomasmorgan** [Ruben222/Social-learning-spite#5]
This code is risky:

```
function processTransmit(transmissions){
  numTransmissions = numTransmissions + 1;
  potID = transmissions[0].info_id;
  donID = transmissions[1].info_id;
  leftoverID = transmissions[2].info_id;
  scoreID = transmissions[3].info_id;
  dallinger.getInfo(my_node_id, potID)
    .done(function(resp) {
        pot = resp.info.contents;
    });
  dallinger.getInfo(my_node_id, donID)
    .done(function(resp) {
        donation = resp.info.contents; 
    });
  dallinger.getInfo(my_node_id, leftoverID)
    .done(function(resp) {
        leftovers = resp.info.contents; 
    });
  dallinger.getInfo(my_node_id, scoreID)
    .done(function(resp) {
        totalScore = resp.info.contents; 
    });
  setTimeout(function() { // Wait X seconds to allow the above functions to run + add believable delay
    showResults(pot, donation, leftovers, totalScore);
  }, 2000);
}
```

It won't actually wait for these requests to finish and just gambles they will complete within 2 seconds.

**Comment by thomasmorgan** [comment]
This is resolved (and tidied up) in this commit: d20f852bb8cf7a4fd3d310f0d4c47aa21f10456d

Consider testing and merging

**Comment by Rowatsonn** [comment]
If you have a better way of achieving this then I'm all for that. I agree, what I did was pretty risky. I just wasn't sure how to fix it so (as per) I just did something substandard and hoped for the best!

**Comment by thomasmorgan** [comment]
No worries, getting around synchronous requests can be a hassle. Can you test my code? If it works then we are good to go, but I don't want to introduce bugs!

**Comment by thomasmorgan** [comment]
I think this has been tested, so I will close the issue.
