### ISSUE TITLE
Possibly inconsistent partner id?

### ISSUE THREAD

**Issue by thomasmorgan** [Ruben222/Social-learning-spite#6]
In the 2nd part of the experiment, you show their partner id as:

```
$("#partnerid").html("Your partner is Participant " + (parseInt(dallinger.identity.participantId) + 1));
```

but also as

```
$("#Socialinfo").html("Participant " + (parseInt(dallinger.identity.participantId) + 2) + " in your group decided to: ");
```

Aren't these different numbers?

**Comment by Rowatsonn** [comment]
They are supposed to be different. I know since you typed this we have briefly discussed the experiment over email so I think we went over the answer. But basically, it stems from wanting the partners to be different between each part.

**Comment by thomasmorgan** [comment]
Sounds good, I will close the issue
